{{- if .Values.upsmon.enabled }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "nut.fullname" . }}-upsmon
  labels: {{ include "nut.labels" . | nindent 4 }}
  {{- range $key, $val := .Values.upsmon.labels }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  annotations:
    {{- if .Values.upsmon.annotations }}
    {{- toYaml .Values.upsmon.annotations | nindent 4 }}
    {{- end }}
spec:
  updateStrategy:
    type: {{ .Values.upsmon.updateStrategy }}
    {{- if eq .Values.upsmon.updateStrategy "RollingUpdate"}}
    rollingUpdate:
      maxUnavailable: {{ .Values.upsmon.maxUnavailable }}
    {{- end}}
  selector:
    matchLabels: {{ include "nut.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "nut.selectorLabels" . | nindent 8 }}
        {{- range $key, $val := .Values.upsmon.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/upsmon/config.yaml") . | sha256sum }}
        {{- if .Values.upsmon.podAnnotations }}
        {{- toYaml .Values.upsmon.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "nut.fullname" . }}-upsmon
        {{- if .Values.upsmon.extraVolumes }}
        {{- toYaml .Values.upsmon.extraVolumes | nindent 8 }}
        {{- end }}
      {{- if .Values.upsmon.serviceAccount.create }}
      serviceAccountName: {{ include "nut.serviceAccountName" . }}-upsmon
      {{- end }}
      securityContext:
        {{- toYaml .Values.upsmon.securityContext | nindent 8 }}
      containers:
        - name: upsmon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.upsmon.containerSecurityContext | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/nut/upsmon.conf
              subPath: upsmon.conf
            {{- if .Values.upsmon.extraVolumeMounts }}
            {{- toYaml .Values.upsmon.extraVolumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.upsmon.resources | nindent 12 }}
      {{- with .Values.upsmon.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.upsmon.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.upsmon.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.upsmon.nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}
