{{- if and .Values.upsmon.enabled .Values.upsmon.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nut.serviceAccountName" . }}-upsmon
  labels:
    {{- include "nut.labels" . | nindent 4 }}
  {{- with .Values.upsmon.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
