{{- $isDummy := false -}}
{{- if .Values.ups }}
{{- $isDummy = eq ((index .Values.ups 0).driver) "dummy-ups" -}}
{{- end }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nut.fullname" . }}
  labels: {{ include "nut.labels" . | nindent 4 }}
data:
  upsd.conf: |
    LISTEN  0.0.0.0
  ups.conf: |
    {{- range .Values.ups }}
    [{{ .name }}]
    driver = {{ .driver | default "usbhid-ups" }}
    port = {{ .port | default "auto" }}
    vendorid = {{ .vendorid }}
    desc = {{ .description | quote }}
    sdorder = {{ .sdorder | default 1 }}
    {{- end }}
  upsd.users: |
    [admin]
    password = admin
    upsmon secondary  
  {{- if $isDummy }}
  dummy.seq: |
    {{- .Files.Get "examples/dummy.seq" | nindent 4 }}
  {{- end }}
