{{- if .Values.ups }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nut.fullname" . }}
  labels:
    {{- include "nut.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: upsd
      protocol: TCP
      name: upsd
  selector:
    {{- include "nut.selectorLabels" . | nindent 4 }}
{{- end }}
