{{- if and .Values.ups .Values.exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nut.fullname" . }}-exporter
type: Opaque
stringData:
  username: admin
  password: admin
{{- end }}
