{{- if and .Values.ups .Values.exporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nut.fullname" . }}-exporter
  labels:
    {{- include "nut.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: exporter
      protocol: TCP
      name: exporter
  selector:
    {{- include "nut.selectorLabels" . | nindent 4 }}
{{- end }}
