name: Release Charts

on:
  workflow_run:
    workflows: ["Helm Chart linting"]
    types:
      - completed
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Install Helm
      #   uses: azure/setup-helm@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::642939544760:role/HelmChartPublish
          aws-region: us-east-2

      - name: Helm release
        uses: shellbear/helm-release-action@0.1
        with:
          repo: s3://repos.imartin.net/
          chart: ./helm/nut
