name: Shell code checks

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
